-- RULE: This table ONLY INSERT. No migration UPDATE/DELETE data here,
-- Only add new col (if needed) additive, no broke old data.

CREATE TABLE events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type      VARCHAR(100) NOT NULL, -- Used for many Aggregate (Stock, Order...)
    aggregate_id        VARCHAR(100) NOT NULL,
    event_type          VARCHAR(100) NOT NULL,
    payload             JSONB        NOT NULL,
    aggregate_version   BIGINT       NOT NULL,
    occurred_at         TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uq_aggregate_version UNIQUE (aggregate_id, aggregate_version)
);

-- Index combine type & id for fast load
CREATE INDEX idx_events_aggregate ON events (aggregate_type, aggregate_id);