-- Read model summary — instead of replaying all events when queried.
-- Use for GET /stock/{warehouse}/{sku} mostly.

CREATE TABLE stock_summary_read_model (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code    VARCHAR(20)  NOT NULL,
    sku_code          VARCHAR(50)  NOT NULL,
    quantity          INT          NOT NULL DEFAULT 0,
    last_movement_at  TIMESTAMP,

    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_stock_summary UNIQUE (warehouse_code, sku_code)
);