-- Reads the inventory model by LOT — supports FEFO (First-Expiry-First-Out) reporting.
-- IMPORTANT: This is an approximation, not the source of truth.
-- Reason: event StockPicked/StockAdjusted currently do NOT carry information regarding "which lot was issued from"
-- (domain model Phase 1 normalization, selecting a lot during stock issuance is not mandatory).

-- Projection infers this using FEFO (deducting from the oldest lot first)
-- If actual business operations require 100% accuracy regarding lots:
-- add field lotNumber to StockPicked event & force to pick lot before API pick.

CREATE TABLE stock_lot_read_model (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code    VARCHAR(20)  NOT NULL,
    sku_code          VARCHAR(50)  NOT NULL,
    lot_number        VARCHAR(50)  NOT NULL,
    quantity          INT          NOT NULL DEFAULT 0,
    received_at       TIMESTAMP    NOT NULL,   -- first import of this lot => sort FEFO

    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_stock_lot UNIQUE (warehouse_code, sku_code, lot_number)
);

CREATE INDEX idx_stock_lot_lookup ON stock_lot_read_model (warehouse_code, sku_code, received_at);
