-- Read model aggregating daily fluctuations — to support trend reports/dashboards
-- (e.g., "inventory over the past 30 days" chart), avoiding the need to query and group raw events every time a chart is rendered.

CREATE TABLE stock_daily_movement_read_model (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code    VARCHAR(20)  NOT NULL,
    sku_code          VARCHAR(50)  NOT NULL,
    movement_date     DATE         NOT NULL,
    total_received    INT          NOT NULL DEFAULT 0,
    total_picked      INT          NOT NULL DEFAULT 0,
    total_adjusted    INT          NOT NULL DEFAULT 0,  -- can be negative

    CONSTRAINT uq_stock_daily UNIQUE (warehouse_code, sku_code, movement_date)
);

CREATE INDEX idx_stock_daily_lookup ON stock_daily_movement_read_model (warehouse_code, sku_code, movement_date);
